"use client";

import { useSearchParams } from "next/navigation";
import Link from "next/link";

export default function TripPage() {
  const searchParams = useSearchParams();

  const destination =
    searchParams.get("destination") || "Jaipur";

  const budget =
    searchParams.get("budget") || "5000";

  const travelers =
    searchParams.get("travelers") || "4";

  const days =
    searchParams.get("days") || "3";

  const startingCity =
    searchParams.get("startingCity") || "Delhi";

  return (
    <main className="min-h-screen bg-gray-100 py-10 px-6">
      <div className="mx-auto max-w-6xl">

        {/* Header */}

        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-5xl font-bold text-gray-900">
              ✈️ Your Trip is Ready
            </h1>

            <p className="mt-2 text-lg text-gray-600">
              Your personalized travel plan generated by AI.
            </p>
          </div>

          <Link
            href="/"
            className="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white transition hover:bg-indigo-700"
          >
            Plan Another Trip
          </Link>
        </div>

        {/* Trip Summary */}

        <section className="rounded-2xl bg-white p-8 shadow-lg">

          <h2 className="mb-6 text-3xl font-bold">
            📍 {destination}
          </h2>

          <div className="grid gap-6 md:grid-cols-4">

            <SummaryCard
              title="Starting City"
              value={startingCity}
              color="bg-indigo-50"
            />

            <SummaryCard
              title="Budget"
              value={`₹${budget}`}
              color="bg-green-50"
            />

            <SummaryCard
              title="Travelers"
              value={travelers}
              color="bg-yellow-50"
            />

            <SummaryCard
              title="Days"
              value={days}
              color="bg-orange-50"
            />

          </div>
        </section>

        {/* Recommendations */}

        <section className="mt-8 grid gap-6 md:grid-cols-2">

          <InfoCard
            emoji="🚆"
            title="Recommended Transport"
            description="Train (Recommended for budget-friendly travel)"
          />

          <InfoCard
            emoji="🏨"
            title="Recommended Hotel"
            description={`Zostel ${destination}`}
          />

        </section>

        {/* Itinerary */}

        <section className="mt-8 rounded-2xl bg-white p-8 shadow-lg">

          <h2 className="mb-6 text-3xl font-bold">
            🗺️ Suggested Itinerary
          </h2>

          <div className="space-y-5">

            <DayCard
              day={1}
              activity={`Explore famous attractions in ${destination}.`}
            />

            <DayCard
              day={2}
              activity="Local sightseeing, markets and food tour."
            />

            <DayCard
              day={3}
              activity="Shopping and return journey."
            />

          </div>

        </section>

      </div>
    </main>
  );
}

type SummaryCardProps = {
  title: string;
  value: string;
  color: string;
};

function SummaryCard({
  title,
  value,
  color,
}: SummaryCardProps) {
  return (
    <div className={`rounded-xl p-5 ${color}`}>
      <p className="text-sm text-gray-500">
        {title}
      </p>

      <p className="mt-2 text-xl font-bold">
        {value}
      </p>
    </div>
  );
}

type InfoCardProps = {
  emoji: string;
  title: string;
  description: string;
};

function InfoCard({
  emoji,
  title,
  description,
}: InfoCardProps) {
  return (
    <div className="rounded-2xl bg-white p-6 shadow-lg">
      <h2 className="mb-4 text-2xl font-bold">
        {emoji} {title}
      </h2>

      <p className="text-gray-700">
        {description}
      </p>
    </div>
  );
}

type DayCardProps = {
  day: number;
  activity: string;
};

function DayCard({
  day,
  activity,
}: DayCardProps) {
  return (
    <div className="rounded-xl border border-gray-200 bg-gray-50 p-5">
      <h3 className="text-lg font-bold">
        Day {day}
      </h3>

      <p className="mt-2 text-gray-700">
        {activity}
      </p>
    </div>
  );
}