import Link from "next/link";

export default function TripHeader() {
  return (
    <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-center">
      <div>
        <h1 className="text-5xl font-bold text-gray-900">
          ✈️ Your Trip is Ready
        </h1>

        <p className="mt-2 text-lg text-gray-600">
          Your personalized travel plan generated by AI.
        </p>
      </div>

      <Link
        href="/"
        className="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white transition hover:bg-indigo-700"
      >
        Plan Another Trip
      </Link>
    </div>
  );
}